
ALTER TABLE Record MODIFY COLUMN title TINYTEXT;
ALTER TABLE Record MODIFY COLUMN strategy TEXT;
ALTER TABLE Record ADD COLUMN review TEXT;
ALTER TABLE Record ADD COLUMN retro TEXT;

CREATE TABLE Estimate(...);

