CREATE TABLE Period(...);
CREATE TABLE Latest(...);

ALTER TABLE Company DROP COLUMN shares_float;

ALTER TABLE Financial DROP COLUMN eps;

ALTER TABLE Financial ADD COLUMN cogs DECIMAL(8, 2) NOT NULL DEFAULT '0';
ALTER TABLE Financial MODIFY COLUMN cogs DECIMAL(8, 2) NOT NULL;

ALTER TABLE Financial ADD COLUMN op_exp DECIMAL(8, 2) NOT NULL DEFAULT '0';
ALTER TABLE Financial MODIFY COLUMN op_exp DECIMAL(8, 2) NOT NULL;

ALTER TABLE Record RENAME COLUMN ps TO p_rev;
ALTER TABLE Record MODIFY COLUMN p_rev DECIMAL(6, 2);

ALTER TABLE Record RENAME COLUMN pe TO p_net;
ALTER TABLE Record MODIFY COLUMN p_net DECIMAL(6, 2);

ALTER TABLE Record ADD COLUMN p_gross DECIMAL(6, 2);
ALTER TABLE Record ADD COLUMN p_oper DECIMAL(6, 2);
ALTER TABLE Record ADD COLUMN asset_quantity DECIMAL(8, 4);
ALTER TABLE Record ADD COLUMN asset_price DECIMAL(10, 4);




