
quarkus.datasource.jdbc.url=${JDBC_URL}
quarkus.datasource.db-kind=${DB_KIND}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.http.port=${HTTP_PORT}
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${FRONTEND_ORIGIN}

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/docs

firebase.db.url=${FIREBASE_DB_URL}
firebase.mode=real
quarkus.google.cloud.project-id=${FIREBASE_PROJECT_ID}
quarkus.google.cloud.service-account-location=${FIREBASE_CREDENTIALS_PATH}

finnhub.api.url=${FINNHUB_API_URL}
finnhub.apikey=${FINNHUB_API_KEY:}
finnhub.mode=real

polygon.api.url=${POLYGON_API_URL}
polygon.apikey=${POLYGON_API_KEY:}
polygon.mode=real

alphavantage.api.url=${ALPHAVANTAGE_API_URL}
alphavantage.apikey=${ALPHAVANTAGE_API_KEY:}
alphavantage.mode=real

gemini.api.url=${GEMINI_API_URL}
gemini.apikey=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-3.1-pro-preview}
gemini.mode=real
